[phases.setup]
nixPkgs = [
    'php82', 
    'php82Extensions.bcmath', 
    'php82Extensions.mbstring', 
    'php82Extensions.pdo_mysql',
    'php82Extensions.gd',
    'php82Extensions.zip',
    'nodejs_20'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci --ignore-scripts'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan event:cache'
]

[start]
cmd = 'bash start.sh'